base_url = "https://boykush.github.io/wiki/"
title = "Kush's Wiki"
lang_code = "ja"
description = "boykushのナレッジ置き場"
favicon = "https://gist.github.com/boykush/3bbc68b5d2580374c97d4336b87fb70f/raw/a838b8f3584b21bcbbe4dd53afca380fe18695a7/boykush_icon.png"
timezone="Asia/Tokyo"
color_scheme="only_dark"
build_search_index = true
sort_key="linked_count"
paginate_by=50
